ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ com.example.ApplicationKt.module ]
  }
}

db {
  jdbcUrl = "jdbc:postgresql://localhost:5433/app_db"
  username = "app_user"
  password = "app_password"
  driver = "org.postgresql.Driver"
  maximumPoolSize = 10
}

